In [23]:
# !/opt/homebrew/bin/python3.13 -m venv ~/venvs/py313
# !source ~/venvs/py313/bin/activate
# !pip install --upgrade pip
# !pip install ipykernel jupyter


In [24]:
# !python -m ipykernel install --user --name py313 --display-name "Python 3.13 (venv)"


In [25]:
#!pip install numpy matplotlib seaborn scikit-learn

In [26]:
#!pip install chardet

In [27]:
import chardet

with open('DataCo_UTF8.csv', 'rb') as f:
    print(chardet.detect(f.read(50000)))  # đọc 50KB đầu tiên để đoán encoding


{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}


In [28]:
# import pandas as pd

# df = pd.read_csv('DataCoSupplyChainDataset.csv')
# df.head()

In [29]:
import pandas as pd

# Đúng cú pháp
df = pd.read_csv('DataCo_UTF8.csv', encoding='utf-8')  # hoặc encoding='ISO-8859-1'
df.head()


Type  Days for shipping (real)  Days for shipment (scheduled)  \
0     DEBIT                         3                              4   
1  TRANSFER                         5                              4   
2      CASH                         4                              4   
3     DEBIT                         3                              4   
4   PAYMENT                         2                              4   

   Benefit per order  Sales per customer   Delivery Status  \
0          91.250000          314.640015  Advance shipping   
1        -249.089996          311.359985     Late delivery   
2        -247.779999          309.720001  Shipping on time   
3          22.860001          304.809998  Advance shipping   
4         134.210007          298.250000  Advance shipping   

   Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                   0           73  Sporting Goods        Caguas  ...   
1                   1           73  Sporting Goods        Caguas  ...   
2                   0           73  Sporting Goods      San Jose  ...   
3                   0           73  Sporting Goods   Los Angeles  ...   
4                   0           73  Sporting Goods        Caguas  ...   

  Order Zipcode Product Card Id Product Category Id  Product Description  \
0           NaN            1360                  73                  NaN   
1           NaN            1360                  73                  NaN   
2           NaN            1360                  73                  NaN   
3           NaN            1360                  73                  NaN   
4           NaN            1360                  73                  NaN   

                                  Product Image  Product Name Product Price  \
0  http://images.acmesports.sports/Smart+watch   Smart watch         327.75   
1  http://images.acmesports.sports/Smart+watch   Smart watch         327.75   
2  http://images.acmesports.sports/Smart+watch   Smart watch         327.75   
3  http://images.acmesports.sports/Smart+watch   Smart watch         327.75   
4  http://images.acmesports.sports/Smart+watch   Smart watch         327.75   

  Product Status shipping date (DateOrders)   Shipping Mode  
0              0             2/3/2018 22:56  Standard Class  
1              0            1/18/2018 12:27  Standard Class  
2              0            1/17/2018 12:06  Standard Class  
3              0            1/16/2018 11:45  Standard Class  
4              0            1/15/2018 11:24  Standard Class  

[5 rows x 53 columns]

## Look

In [30]:
df.info()

df.describe()

df.isnull().sum()

#df.dropna(inplace=True)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Type                           180519 non-null  object 
 1   Days for shipping (real)       180519 non-null  int64  
 2   Days for shipment (scheduled)  180519 non-null  int64  
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object 
 6   Late_delivery_risk             180519 non-null  int64  
 7   Category Id                    180519 non-null  int64  
 8   Category Name                  180519 non-null  object 
 9   Customer City                  180519 non-null  object 
 10  Customer Country               180519 non-null  object 
 11  Customer Email                 180519 non-null  object 
 12  Customer Fname                

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0


In [31]:
# Liệt kê cột nào là kiểu object
object_columns = df.select_dtypes(include=['object']).columns
print("Các cột kiểu object:", object_columns)
#Liệt kê cột nào là kiểu số
numeric_columns = df.select_dtypes(include=['number']).columns
print("Các cột kiểu số:", numeric_columns)

Các cột kiểu object: Index(['Type', 'Delivery Status', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Department Name', 'Market',
       'Order City', 'Order Country', 'order date (DateOrders)',
       'Order Region', 'Order State', 'Order Status', 'Product Image',
       'Product Name', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')
Các cột kiểu số: Index(['Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Late_delivery_risk',
       'Category Id', 'Customer Id', 'Customer Zipcode', 'Department Id',
       'Latitude', 'Longitude', 'Order Customer Id', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Qu

In [32]:
#Liệt kê giá trị unique của mỗi cột kiểu object và in ra tất cả giá trị unique của các cột kiểu object


for col in object_columns:
    unique_values = df[col].unique()
    print(f"Cột '{col}' có {len(unique_values)} giá trị duy nhất:")
    # print(unique_values[:15])  # In ra 15 giá trị đầu tiên
    print(unique_values) # In ra tất cả giá trị unique
    print("\n")



Cột 'Type' có 4 giá trị duy nhất:
['DEBIT' 'TRANSFER' 'CASH' 'PAYMENT']


Cột 'Delivery Status' có 4 giá trị duy nhất:
['Advance shipping' 'Late delivery' 'Shipping on time' 'Shipping canceled']


Cột 'Category Name' có 50 giá trị duy nhất:
['Sporting Goods' 'Cleats' 'Shop By Sport' "Women's Apparel" 'Electronics'
 'Boxing & MMA' 'Cardio Equipment' 'Trade-In' "Kids' Golf Clubs"
 'Hunting & Shooting' 'Baseball & Softball' "Men's Footwear"
 'Camping & Hiking' 'Consumer Electronics' 'Cameras ' 'Computers'
 'Basketball' 'Soccer' "Girls' Apparel" 'Accessories' "Women's Clothing"
 'Crafts' "Men's Clothing" 'Tennis & Racquet' 'Fitness Accessories'
 'As Seen on  TV!' 'Golf Balls' 'Strength Training' "Children's Clothing"
 'Lacrosse' 'Baby ' 'Fishing' 'Books ' 'DVDs' 'CDs ' 'Garden' 'Hockey'
 'Pet Supplies' 'Health and Beauty' 'Music' 'Video Games' 'Golf Gloves'
 'Golf Bags & Carts' 'Golf Shoes' 'Golf Apparel' "Women's Golf Clubs"
 "Men's Golf Clubs" 'Toys' 'Water Sports' 'Indoor/Outdoor Games'

In [33]:
# Liệt kê các cột kiểu số và in ra tất cả giá trị unique của các cột kiểu số

for col in numeric_columns:
    unique_values = df[col].unique()
    print(f"Cột '{col}' có {len(unique_values)} giá trị duy nhất:")
    # print(unique_values[:15])  # In ra 15 giá trị đầu tiên
    print(unique_values) # In ra tất cả giá trị unique
    print("\n")



Cột 'Days for shipping (real)' có 7 giá trị duy nhất:
[3 5 4 2 6 0 1]


Cột 'Days for shipment (scheduled)' có 4 giá trị duy nhất:
[4 1 2 0]


Cột 'Benefit per order' có 21998 giá trị duy nhất:
[  91.25      -249.0899963 -247.7799988 ... -103.9700012 -237.5899963
 -337.1000061]


Cột 'Sales per customer' có 2927 giá trị duy nhất:
[314.6400146 311.3599854 309.7200012 ... 298.769989  403.7099915
 474.7600098]


Cột 'Late_delivery_risk' có 2 giá trị duy nhất:
[0 1]


Cột 'Category Id' có 51 giá trị duy nhất:
[73 17 29 24 13 12  9 41 37 38 44  3 18 43 65 62 64  4  2 26 40 76 66 70
  6 11 16 36 10 63  5 60 45 59 67 61 68  7 72 69 71 75 35 34 33 32 31 30
 74 48 46]


Cột 'Customer Id' có 20652 giá trị duy nhất:
[20755 19492 19491 ... 18579 16244  2677]


Cột 'Customer Zipcode' có 996 giá trị duy nhất:
[  725. 95125. 90027. 14150. 33162. 94583. 11520. 93905.  1960.   729.
 90723. 60056. 90813. 95670. 59102. 18702. 48066. 90706. 60187. 48238.
 75220. 17013. 75228. 19702. 91402. 30318. 94539. 1

In [34]:
#Liệt kê giá trị unique của mỗi cột kiểu object
print("Các giá trị duy nhất của các cột kiểu object:")
for col in object_columns:
    print(f"Cột {col} có {df[col].nunique()} giá trị duy nhất")
    print(df[col].unique()[:10])  # In ra 10 giá trị đầu tiên
    print()
# xuất ra file CSV
df[object_columns].nunique().to_csv('unique_object_columns.csv', header=True)
# Thống kê số lượng giá trị duy nhất của mỗi cột
unique_counts = df.nunique()
print(unique_counts)    
# xuất ra file CSV
unique_counts.to_csv('unique_counts.csv', header=True)

Các giá trị duy nhất của các cột kiểu object:
Cột Type có 4 giá trị duy nhất
['DEBIT' 'TRANSFER' 'CASH' 'PAYMENT']

Cột Delivery Status có 4 giá trị duy nhất
['Advance shipping' 'Late delivery' 'Shipping on time' 'Shipping canceled']

Cột Category Name có 50 giá trị duy nhất
['Sporting Goods' 'Cleats' 'Shop By Sport' "Women's Apparel" 'Electronics'
 'Boxing & MMA' 'Cardio Equipment' 'Trade-In' "Kids' Golf Clubs"
 'Hunting & Shooting']

Cột Customer City có 563 giá trị duy nhất
['Caguas' 'San Jose' 'Los Angeles' 'Tonawanda' 'Miami' 'San Ramon'
 'Freeport' 'Salinas' 'Peabody' 'Canovanas']

Cột Customer Country có 2 giá trị duy nhất
['Puerto Rico' 'EE. UU.']

Cột Customer Email có 1 giá trị duy nhất
['XXXXXXXXX']

Cột Customer Fname có 782 giá trị duy nhất
['Cally' 'Irene' 'Gillian' 'Tana' 'Orli' 'Kimberly' 'Constance' 'Erica'
 'Nichole' 'Oprah']

Cột Customer Lname có 1109 giá trị duy nhất
['Holloway' 'Luna' 'Maldonado' 'Tate' 'Hendricks' 'Flowers' 'Terrell'
 'Stevens' 'Olsen' 'Delacruz'

In [35]:
#Liệt kê giá trị unique của mỗi cột kiểu số
for col in numeric_columns:
    print(f"Cột {col} có {df[col].nunique()} giá trị duy nhất")
    print(df[col].unique()[:10])  # In ra 10 giá trị đầu tiên
    print()
# xuất ra file CSV
df[numeric_columns].nunique().to_csv('unique_numeric_columns.csv', header=True)
# Thống kê số lượng giá trị duy nhất của mỗi cột
unique_counts_numeric = df[numeric_columns].nunique()
print(unique_counts_numeric)    
# xuất ra file CSV
unique_counts_numeric.to_csv('unique_counts_numeric.csv', header=True)


Cột Days for shipping (real) có 7 giá trị duy nhất
[3 5 4 2 6 0 1]

Cột Days for shipment (scheduled) có 4 giá trị duy nhất
[4 1 2 0]

Cột Benefit per order có 21998 giá trị duy nhất
[  91.25       -249.0899963  -247.7799988    22.86000061  134.2100067
   18.57999992   95.18000031   68.43000031  133.7200012   132.1499939 ]

Cột Sales per customer có 2927 giá trị duy nhất
[314.6400146 311.3599854 309.7200012 304.8099976 298.25      294.980011
 288.4200134 285.1400146 278.5899963 275.3099976]

Cột Late_delivery_risk có 2 giá trị duy nhất
[0 1]

Cột Category Id có 51 giá trị duy nhất
[73 17 29 24 13 12  9 41 37 38]

Cột Customer Id có 20652 giá trị duy nhất
[20755 19492 19491 19490 19489 19488 19487 19486 19485 19484]

Cột Customer Zipcode có 995 giá trị duy nhất
[  725. 95125. 90027. 14150. 33162. 94583. 11520. 93905.  1960.   729.]

Cột Department Id có 11 giá trị duy nhất
[ 2  4  5  3  6  7 10  8  9 11]

Cột Latitude có 11250 giá trị duy nhất
[18.2514534  18.27945137 37.29223251 34.125